
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: true
    ansible_become_method: sudo 
  children:
    massa:
      hosts:
        server01.example.com:
          user: admin
          user_passwd: "{{ host_user_passwd }}"
          root_passwd: "{{ host_root_passwd }}"
          ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub')  }}"
          ansible_become_pass: "{{ host_user_passwd }}"
          cfg_static_network: false
          ansible_port: 11122
          ansible_host: (SERVER IP)
       